development:
  sessions:
    default:
      #uri: 'MONGOLAB_URI=mongodb://heroku_app16903621_A:kXoCSDklVlQABfkULmYEdmEkuuXPvuhg@ds027709.mongolab.com:27709/heroku_app16903621'
      database: actress_app_dev
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: actress_app_test
      hosts:
        - localhost:27017
      options:
production:
  sessions:
    default:
      # uri: <%= ENV['MONGOHQ_DB_URL'] %>
      uri: <%= ENV['MONGOLAB_URI'] %>
