require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActressesController do

  # This should return the minimal set of attributes required to create a valid
  # Actress. As you add validations to Actress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all actresses as @actresses" do
      actress = Actress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:actresses).should eq([actress])
    end
  end

  describe "GET show" do
    it "assigns the requested actress as @actress" do
      actress = Actress.create! valid_attributes
      get :show, {:id => actress.to_param}, valid_session
      assigns(:actress).should eq(actress)
    end
  end

  describe "GET new" do
    it "assigns a new actress as @actress" do
      get :new, {}, valid_session
      assigns(:actress).should be_a_new(Actress)
    end
  end

  describe "GET edit" do
    it "assigns the requested actress as @actress" do
      actress = Actress.create! valid_attributes
      get :edit, {:id => actress.to_param}, valid_session
      assigns(:actress).should eq(actress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Actress" do
        expect {
          post :create, {:actress => valid_attributes}, valid_session
        }.to change(Actress, :count).by(1)
      end

      it "assigns a newly created actress as @actress" do
        post :create, {:actress => valid_attributes}, valid_session
        assigns(:actress).should be_a(Actress)
        assigns(:actress).should be_persisted
      end

      it "redirects to the created actress" do
        post :create, {:actress => valid_attributes}, valid_session
        response.should redirect_to(Actress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved actress as @actress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Actress.any_instance.stub(:save).and_return(false)
        post :create, {:actress => { "name" => "invalid value" }}, valid_session
        assigns(:actress).should be_a_new(Actress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Actress.any_instance.stub(:save).and_return(false)
        post :create, {:actress => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested actress" do
        actress = Actress.create! valid_attributes
        # Assuming there are no other actresses in the database, this
        # specifies that the Actress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Actress.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => actress.to_param, :actress => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested actress as @actress" do
        actress = Actress.create! valid_attributes
        put :update, {:id => actress.to_param, :actress => valid_attributes}, valid_session
        assigns(:actress).should eq(actress)
      end

      it "redirects to the actress" do
        actress = Actress.create! valid_attributes
        put :update, {:id => actress.to_param, :actress => valid_attributes}, valid_session
        response.should redirect_to(actress)
      end
    end

    describe "with invalid params" do
      it "assigns the actress as @actress" do
        actress = Actress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Actress.any_instance.stub(:save).and_return(false)
        put :update, {:id => actress.to_param, :actress => { "name" => "invalid value" }}, valid_session
        assigns(:actress).should eq(actress)
      end

      it "re-renders the 'edit' template" do
        actress = Actress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Actress.any_instance.stub(:save).and_return(false)
        put :update, {:id => actress.to_param, :actress => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested actress" do
      actress = Actress.create! valid_attributes
      expect {
        delete :destroy, {:id => actress.to_param}, valid_session
      }.to change(Actress, :count).by(-1)
    end

    it "redirects to the actresses list" do
      actress = Actress.create! valid_attributes
      delete :destroy, {:id => actress.to_param}, valid_session
      response.should redirect_to(actresses_url)
    end
  end

end
